### ISSUE TITLE
Feature Request: Anime-Loads Logindaten speichern (non-interactive)

### ISSUE THREAD

**Issue by Pheromir** [Pfuenzle/anime-loads#10]
Hey,

Wäre ganz cool, wenn man eventuell auch für AL die Logindaten (wie bei MyJDL) in der Config hinterlegen könnte, damit man im non-interactive mode angemeldet werden kann (damit die DL-Markierung bei AL gesetzt wird etc).
Könnte eventuell auch wegen Captchas interessant sein, wenn man einen VIP-Account hat.

(Ich benutze z.B. aktuell das Docker-Image auf meinem NAS, wodurch eine interaktive Anmeldung eher hinderlich ist)

Danke im voraus :D

**Comment by Pfuenzle** [comment]
Ja, kann ich gerne hinzufügen, denke ich werde am Wochenende dazu kommen
