### ISSUE TITLE
ARM

### ISSUE THREAD

**Issue by CircaShoes** [Pfuenzle/anime-loads#12]
Hallo,

ich bin noch nicht solange auf Github unterwegs, deswegen weiß ich sonst nicht wie ich dich konaktieren kann, aber kannst du die docker Image auch ARM fähig machen, damit ich das auf einer QNAP installieren kann?

MFG DeagX

**Comment by Pheromir** [comment]
Hey,

Ich hab zwar selbst nicht wirklich viel Ahnung von Docker-Images und erst recht nicht von ARM; aber weißt du welche ARM Architektur (dein) QNAP nutzt?
Unter arm7 auf meinem Raspberry Pi konnte ich kein Image builden, da numpy (Python dependency) dafür wohl nicht angeboten wird und nicht gebuildet werden konnte. Bei arm64 hingegen schon, so dass ich dafür ein Image builden konnte. 

Das Image hat im Test ein wenig rumgezickt und beim download im ersten Durchlauf z.B. einen Fehler (`Error:
the JSON object must be str, bytes or bytearray, not NoneType`) rausgehauen, aber im 2. Durchlauf den Download erfolgreich beim JD über MyJD hinzugefügt.

![Docker_Desktop_2021-08-24-08-15-17](https://user-images.githubusercontent.com/13359741/130565820-281d6e86-ffe6-4e5f-a2a3-a2782bc59b58.png)

Falls es bei dir also rein zufällig auch arm64 sein sollte, hättest du eventuell Glück. Ich kann nachher mal schauen ob ich das Image aufn Repository bekomme, aber DockerHub will mir aktuell keine Bestätigungsmail zusenden :^)

**Comment by CircaShoes** [comment]
Hallo,Danke für deine Antwort, leider ist es ein 32bit ARM Prozessor, ich kenn mich leider selber nicht gut aus mit Docker, hatte bei dir die Hoffnung :D--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 24.08.21, 08:17 schrieb Pheromir ***@***.***>:

   
  Hey, 
  Ich hab zwar selbst nicht wirklich viel Ahnung von Docker-Images und erst recht nicht von ARM; aber weißt du welche ARM Architektur (dein) QNAP nutzt? Unter arm7 auf meinem Raspberry Pi konnte ich kein Image builden, da numpy (Python dependency) dafür wohl nicht angeboten wird und nicht gebuildet werden konnte. Bei arm64 hingegen schon, so dass ich dafür ein Image builden konnte. 
  Das Image hat im Test ein wenig rumgezickt und beim download im ersten Durchlauf z.B. einen Fehler (Error: the JSON object must be str, bytes or bytearray, not NoneType) rausgehauen, aber im 2. Durchlauf den Download erfolgreich beim JD über MyJD hinzugefügt. 
   
  Falls es bei dir also rein zufällig auch arm64 sein sollte, hättest du eventuell Glück. Ich kann nachher mal schauen ob ich das Image aufn Repository bekomme, aber DockerHub will mir aktuell keine Bestätigungsmail zusenden :^)

**Comment by Pheromir** [comment]
Okay, schade. Hatte die Hoffnung, dass es dir etwas bringen könnte, aaaaber da hat uns QNAP wohl einen Strich durch die Rechnung gemacht.

Falls das hier nochmal jemand lesen sollte der eventuell arm64 benötigt:
Ein halbwegs funktionierendes Image habe ich jetzt auf [DockerHub](https://hub.docker.com/repository/docker/pheromir/anime-loads) gepushed. Funktionsweise ist quasi wie bei dem normalen Image, so dass die Anleitung aus der Readme genutzt werden kann.
Kleiner Unterschied jedoch: Statt in /config muss der config-Ordner in `/usr/src/app/anime-loads/config` gemounted werden.

**Comment by Pheromir** [comment]
Ich habe es dank etwas Hilfe von einem Kollegen geschafft, auch ein arm7 Image zu basteln. Ich hoffe mal, dass das bei dir laufen sollte. Habe es nur ganz kurz mit einem durchlauf und einem Download geprüft und es schien soweit zu funktionieren.
Das Image ist allerdings alles andere als professionell erstellt, daher kann es eventuell sein dass es nicht sooo gut läuft.

Falls QNAP auch kein arm7 sondern nochmal was anderes nutzt, weiß ich auch nicht mehr groß weiter :D 

Kannst jedenfalls mal testen ob es funktioniert, das Image kannste über DockerHub mit dem Tag `pheromir/anime-loads:armv7` pullen.
![Docker_Desktop_2021-08-25-14-44-27](https://user-images.githubusercontent.com/13359741/130795759-09a39d69-ef14-4827-a80f-ea09ce734fe1.png)

**Comment by CircaShoes** [comment]
Hi,
danke nochmal für die Mega Hilfe, es funktioniert jetzt so teilweise, bei manchen Downloads kommt noch der Fehler:
Error:
Message: connection refused

[ERROR] Fehler beim hinzufügen von Episode 8 von I’m Standing on a Million Lives 2, wird im nächsten Durchlauf erneut versucht. Ist JDownloader gestartet?

aber nach paar durchläufen funktioniert es dann doch, danke für denn mega job

**Comment by Pheromir** [comment]
Ich weiß leider nicht genau ob die connection refused Meldung von anime-loads oder von myjdownloader kommt, aber ich würde mal auf myjdl vermuten.

Ich bin mir nicht sicher wie bei dir das Setup mit JDownloader aussieht, aber bei meinem jDownloader den ich ebenfalls in einem Docker-Container laufen habe, "musste" ich damit es besser funktioniert erst in den Profieinstellungen vom jDownloader bei der Option `MyJDownloader Settings: Custom Device IPs` auf die lokale IP-Adresse des NAS setzen (`[ "192.168.2.111" ]` bei meinem Heimnetzwerk z.B.), damit es etwas besser funktioniert. Vielleicht ist das bei dir auch der Fall, ansonsten wüsste ich nicht groß was noch das Problem sein könnte, wenn man von Standardproblemen wie "PC mit JDownloader hat instabiles Internet" oder so absieht.

Sollte aber vermutlich nicht ganz so tragisch sein, solange die Folgen in einem der nachfolgenden Durchläufe heruntergeladen werden.
