### ISSUE TITLE
Fehler beim bennen der möglichen Downloader

### ISSUE THREAD

**Issue by Mega-Bits** [Pfuenzle/anime-loads#3]
Nur als kleine Anmerkung. Habe da einen Fehler gefunden :)
![unknown](https://user-images.githubusercontent.com/80045566/109969348-b291f200-7ceb-11eb-8df1-0059cb7e5fee.png)
Glaube zumindest das das nicht gewollt ist ;)

**Comment by Pfuenzle** [comment]
Nein, hatte das My von MyJdownloader vergessen, ist gefixt :D
