### ISSUE TITLE
Feature Request: Set Comment on Downloads

### ISSUE THREAD

**Issue by Mega-Bits** [Pfuenzle/anime-loads#4]
Hallo,

ich wollte mal fragen ob es möglich ist die Downloads an JDownloader mit einem Comment zu schicken.
![6753184d](https://user-images.githubusercontent.com/80045566/110000614-6bb3f480-7d0b-11eb-9b77-b322ff4790e4.png)
Weil ich habe ein Skript was die Downloads dem entsprechend bennent und direkt verschiebt in die Richtige Mediathek.

MFG Bits

**Comment by Pfuenzle** [comment]
Ist einfach möglich, mach ich morgen.
Kann das was festes sein, also z.B. immer anime-loads oder sollte da der animetitel oder sowas enthalten sein?

**Comment by Mega-Bits** [comment]
> 
> 
> Ist einfach möglich, mach ich morgen.
> Kann das was festes sein, also z.B. immer anime-loads oder sollte da der animetitel oder sowas enthalten sein?

Mir würde es reichen wenn man da bsp. ein Preset einstellen könnte oder auch einfach in der ani.json einen festlegen könnte. Was halt einfacher ist. Kann das bei mir ja in meinem Skript so anpassen das er alles nehmen kann aber halt nur nicht den Namen des Anime weil das keine Konstante ist auf die ich mit "if" testen könnte ;)

**Comment by Pfuenzle** [comment]
Ich würde in die ani.json einfach noch einen Parameter jd_comment = "" reinmachen,
Da rein könnte dann statischer Text oder Variablen wie {name}, {episode}, oder {Resolution} reingesetzt werden, dann könntest du es anpassen wie du es brauchst. Würde das bei deinem Fall so gehen?
Ich mach es aber evtl so, dass es direkt in der json geändert werden muss, ich will eher nicht, dass man beim ersten Start direkt mit 100 Fragen bombardiert wird

**Comment by Mega-Bits** [comment]
Das klingt interresant. Vielleicht könntest du es auch so machen das wenn man einen Anime added das man dan gefragt wird `"Möchtest du den Download mit einem bestimmten Kommentar an JDownloader übereichen? (leer lassen für nein und help für eine Liste der möglichen Tags)"`

Das klingt dann ja eingetlich selbsterklärend und du würdest die User nicht überladen. Wäre zumindest meine Idee :)

**Comment by Pfuenzle** [comment]
Ja, gute Idee, ich werde es so machen. Dann wäre es allerdings nur bei automatischen Downloads dabei

**Comment by Mega-Bits** [comment]
Ich für meinen Teil nutze dein Tool auch nur da :) Wenn ich was per so zwischen durch brauche ist nichts einfacher als Click and Load auf der Webseite

**Comment by Pfuenzle** [comment]
Ich hab mir grade nochmal die MyJdownloader API angesehen, sieht so aus als würde es doch etwas länger dauern. Ich benutzte momentan für den lokalen JDownloader und MyJdownloader verschieden Funktionen und beide unterstützen keine Comments. Es gibt eine ähnliche Funktion, die Comments unterstützt, allerdings unterstützt die Python API von MyJDownloader diese nicht von haus aus, d.h. ich muss die entweder umschreiben oder selber was schreiben. Ich schau mal was kürzer geht

**Comment by Mega-Bits** [comment]
Mann könnte das Bypassen in dem man das mit dem "Packagizer" plugin machen. Wäre zwar dreckig aber würde gehen. Sprich man packt einfach ein Wort oder eine Phrase in den Packet Namen und mit der macht man dann eine If abfrage.

if [ package.name == *Seasonanime* ]; then
set.comment seasonanime
fi

Dafür müsste man einfach nur die möglichkeit haben den Namen des Packetest in anibot.py vor zu definieren. Das würde halt die Komplette arbeit auf JDownload übertragen und wäre denke dadurch einfacher umsetztbar. Aber es würde halt nur bei dem Client funktionieren, weil die Weboberfläche von my.jdownloader das Plugin nicht unterstützt.

**Comment by Pfuenzle** [comment]
Stimmt, damit ist am einfachsten. In dem Fall werd ich das morgen Mal Mal machen und wenn ich mehr Zeit habe, Kommentare richtig implementieren

**Comment by Mega-Bits** [comment]
Nur ist mir gerade aufgefallen das der Packagizer die Kommentare nur für die RAR Files setzt und nicht in den Packeten :(
Da weiß ich nicht wie ich die mit dem EventScripter extrahieren kann. :/

**Comment by Pfuenzle** [comment]
Falls es so nicht geht, kann ich auch abfragen, ob die Dateien in einen besonderen Unterordner kopiert werden sollen

**Comment by Mega-Bits** [comment]
Das kann man wiederrum mit dem Packagizer machen. Wäre dann
```
if [ package.name == Seasonanime ]; then
set.extrationdir /seasonanime/
fi
```
Dann muss ich mein Script fürs erste umschreiben das es einfach die Location list und darauf reagiert anstatt auf den Comment.

**Comment by Pfuenzle** [comment]
Bin gerade an dem Custom Package naming, also wird das issue hier nicht mehr benötigt
