### ISSUE TITLE
Liste von Anime die nicht Ladbar sind (Keine Releases)

### ISSUE THREAD

**Issue by Mega-Bits** [Pfuenzle/anime-loads#5]
Ich versuche mal in dieser Liste die Anime zu führen die nicht ladbar sind, weil sie laut anibot.py keine Releases haben
Ich habe versucht sie per Link und per Name suche hinzuzufügen, in beiden Fällen kam das gleiche Ergebniss.

**Die Liste der Unfindbaren ;)**
```
https://www.anime-loads.org/media/rezero-kara-hajimeru-isekai-seikatsu-2021
https://www.anime-loads.org/media/yakusoku-no-neverland-2021
```
_Ergänze die Liste sobald ich mehr finde._

**Comment by Pfuenzle** [comment]
Danke für den Report, habs grade gefixt
https://github.com/Pfuenzle/anime-loads/commit/256f3b9f7a4ad204f3ff58a66267f6b2a314e27f
Der Fehler kam, wenn bei Laufzeit ~? stand. Dachte ich hätte das schon gefixt aber jetzt geht es sicher. Hab bei einem möglichen zukünftigen Parsingfehler auch noch eine Fehlerausgabe mit der Zeile hinzugefügt, sodass ich direkt sehen kann, an welchem Attribut der Fehler liegt. Also falls nochmal solche Fehler auftreten einfach kurz ein Issue machen. ^^
