### ISSUE TITLE
Config ist im Hauptverzeichnis

### ISSUE THREAD

**Issue by Mega-Bits** [Pfuenzle/anime-loads#6]
Hey,

habe  eben mal das Update gezogen und beim neu erstellen der Daten ist mir aufgefallen das anibot.py seine Config im Hauptverzeichnis anlegt.

als bsp.
```
/opt/anime-loads/anibot.py
/config/ani.json
```

Habe ungern die Config außerhalb der Anwendung ;)

**Comment by Pfuenzle** [comment]
Das war ein workaround für docker, damit in dem gemounteten Ordner nur die config und nicht die .py liegt. Hab auf meinem Rechner gestern noch einen Check eingebaut, dass er den Pfad nur nimmt, falls die App in docker läuft und es ansonsten neben der .py speichert. Hab das allerdings noch nicht gepusht, kommt heute Mittag :)

**Comment by Mega-Bits** [comment]
Habe das jetzt einfach manuell geändert ;)

**Comment by Pfuenzle** [comment]
Hab für die Configdatei jetzt einen Parameter eingebaut(https://github.com/Pfuenzle/anime-loads/commit/6668d1bafdf0de52bba299c451e7d93856eef120), damit beide Use Cases funktionieren:

--configfile <pfad zur configdatei> (z.B. ./config.txt, /home/user/season_2020.json)

Wenn der Parameter gegeben ist, wird die Config datei als die gegebene gesetzt, falls nicht, fällt das Script standardmäßig auf ./config/ani.json zurück.
Dadurch kann der Container mit /config gemountet werden und du kannst mit--configfile ./ani.json die Configdatei im gleichen Ordner wie das Script haben
