### ISSUE TITLE
Anmelden bei anime-loads nicht mehr möglich

### ISSUE THREAD

**Issue by Mega-Bits** [Pfuenzle/anime-loads#7]
Hey,

beim ausführen von anibot.py wird die abfrage fürs einloggen übersprungen
![image](https://user-images.githubusercontent.com/80045566/110202387-16d5c280-7e60-11eb-919e-1553a125c50f.png)

**Comment by Pfuenzle** [comment]
Startest du es in dem Dockercontainer oder normal?
Und falls nicht in Docker, mit welchem Befehl startest du es?
Bei meinen Test hat der Check eigentlich immer funktioniert

**Comment by Mega-Bits** [comment]
Ubuntu läuft bei mir in docker, und darin starte ich dann per console
anibot.py

Der Start Befehl ist oben im Bild drin.

Pfuenzle <notifications@github.com> schrieb am Sa., 6. März 2021, 10:53:

**Comment by Pfuenzle** [comment]
Ah, dann triggern das die Checks natürlich auch. Ich hoffe du kommst mit den 20 Downloads ohne Logins bis ich das fertig habe aus, sollte heute Mittag fertig sein

**Comment by Mega-Bits** [comment]
Mir das erst aufgefallen weil ich ans Limit gekommen bin xD
Aber kein Stress :)

Pfuenzle <notifications@github.com> schrieb am Sa., 6. März 2021, 11:08:

**Comment by Pfuenzle** [comment]
So, hab es jetzt nochmal geändert.
https://github.com/Pfuenzle/anime-loads/commit/6668d1bafdf0de52bba299c451e7d93856eef120
Ich hab für anibot.py 1einen neue Kommandozeilen Befehl hinzugefügt:
--docker (setzt den Modus auf nicht-interaktiv, nur in dem Modus wird die Anmeldung übersprungen, für den Dockercontainer)
Falls die Flag nicht gesetzt ist, wird das Script normal gestartet und fragt nach einer Anmeldung und ggf. nach dem MyJdownloader Passwort. Sollte so jetzt funktionieren, wäre nett wenn dus kurz ausprobierst und ne Rückmeldung gibtst ^^

**Comment by Mega-Bits** [comment]
also der add Command startet jetzt denn auch
![image](https://user-images.githubusercontent.com/80045566/110207521-e26fff80-7e7b-11eb-94d8-9a0b8b3d6fd2.png)

**Comment by Pfuenzle** [comment]
Ups jetzt funktionierts wieder, musste die Parameterlogik etwas umbauen. Sollte wieder gehen

**Comment by Mega-Bits** [comment]
Jup. Jetzt funkt alles.

Nur ist mir gerade aufgefallen das der Packagizer die Kommentare nur für die RAR Files setzt und nicht den Packeten :(
