### ISSUE TITLE
Feature Request: Custom Package Naming

### ISSUE THREAD

**Issue by Mega-Bits** [Pfuenzle/anime-loads#8]
Hallo,

ich hätte eine neue Idee für ein Feature und zwar das man den Packet Namen in der ani.json festlegen kann mit der die Anime an JDownloader weiter gegeben werden.

Als beispiel:

```
{
            "episodes": 8,
            "missing": [],
            "name": "Cells at Work!!",
            "package_name": "Cells at Work $ep" ##Standart mässig würde das Packet ja hataraku-saibou heißen
            "releaseID": 2,
            "url": "https://www.anime-loads.org/media/hataraku-saibou"
        },
```

Da ich JDownloader in kombination mit Filebot nutze und das Naming nicht immer eindeutig ist, wäre es so möglich ihm alle Daten mit zu geben wie die TVDB ID, die Staffel und die Episode in dem ich sie einfach da eintrage. Das würde auch in meinem Fall die erfragte "Comment" #4 Funktion obsolet machen da man auch die Information aus dem Namen auslesen kann.

MFG Mega-Bits

**Comment by Pfuenzle** [comment]
Okay, also es funktioniert jetzt, tut mir leid, dass es so lange gedauert hat.
Beim hinzufügen eines neuen Anime wird man jetzt gefragt, ob man einen speziellen Paketnamen setzen will.
Wenn du deine bereits vorhandenen ändern willst, kannst du einfach den Parameter
`"customPackage": "meinNeuerName",` zu der .json hinzufügen. Der ist optional, d.h. wenn man ihn bei manchen Anime nicht benötigst, kann er einfach weggelassen werden. Falls du deine JSON schon mit dem "package_name" attribut wie oben verändert hast, kannst du einfach alle vorkommen durch "customPackage" ersetzen.
Hoffe dein Problem ist dadurch gelöst, wenn nicht einfach wieder gerne hier melden

**Comment by Hamm3rhart** [comment]
Hey,
Erstmal Vielen dank. Ich nutzte jetzt auch deinen Docker container. Ist es denn auch möglich die Episoden Nummer durch zu geben?
